name = "WeenieCraft 26.1.2"
author = "Karteufel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b8899bbc56dd9d04f390ab6edf27e549a15c20584da825c2220c1c110b468e0"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
