name = "WeenieCraft 26.1.2"
author = "Karteufel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "481e291b03cfbaebeb1aa4aca070224336ced4cc7fe63cee8c917879b37e0735"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
