name = "WeenieCraft 26.1.2"
author = "Karteufel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8da3e4a7222d1e7c863552411d42dfa87b59f02f1dd3203a7f1770508124bc1b"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
